services:
  btc-app:
    # Replace build with image for production
    build: .
    container_name: btc-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"