server {
    listen 80;
    server_name bitguard.pro www.bitguard.pro;

    location / {
        proxy_pass http://btc-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}